In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Load dataset
df = pd.read_csv('/content/games_dataset.csv')

In [ ]:
df.head(5)

,Game Name,Genre,Platform,Release Year,User Rating
0,Sekiro: Shadows Die Twice,Sports,Nintendo Switch,2014,9.654719
1,Control,Puzzle,Nintendo Switch,2000,3.457386
2,Among Us,Strategy,Nintendo Switch,2007,5.367622
3,Call of Duty: Modern Warfare,Stealth,PlayStation,2005,1.240325
4,League of Legends,Simulation,PC,2021,3.535476

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Game Name     5000 non-null   object
 1   Genre         5000 non-null   object
 2   Platform      5000 non-null   object
 3   Release Year  5000 non-null   int64
 4   User Rating   5000 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 195.4+ KB

In [ ]:
df.shape

(5000, 5)

In [ ]:
df.isnull().sum()

Game Name       0
Genre           0
Platform        0
Release Year    0
User Rating     0
dtype: int64

In [ ]:
#Handle Missing Values
#For Numeric Values
#df['Release Year'] = df['Release Year'].fillna(df['Release Year'].median())
#df['User Rating'] = df['User Rating'].fillna(df['User Rating'].median())

#for Categorical Values
#df['Genre'] = df['Genre'].fillna("Unknown")
#df['Platform'] = df['Platform'].fillna("Unknown")

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#Remove Duplicated Values
#df.drop_duplicates(inplace=True)

In [ ]:
#Handle Anomalous Values
#Replace invalid release year with NaN
df.loc[
    (df['Release Year']<1980)|
    (df['Release Year']>2025),
    "Release Year"
] = np.nan

In [ ]:
df['Release Year'].min()
df['Release Year'].max()

2023.0

In [ ]:
#Replace invalid Ratings with Nan
df.loc[
    (df['User Rating']<0)|
    (df['User Rating']>10),
    "User Rating"
] = np.nan

In [ ]:
df['Genre'].unique()

array(['Sports', 'Puzzle', 'Strategy', 'Stealth', 'Simulation', 'Shooter',
       'Adventure', 'Horror', 'Racing', 'Role-playing', 'Action',
       'Survival', 'Fighting', 'Platformer'], dtype=object)

In [ ]:
#Fill newly created missing values
df['Release Year'] = df['Release Year'].fillna(df['Release Year'].median())
df['User Rating'] = df['User Rating'].fillna(df['User Rating'].median())

In [ ]:
#Standardize Genre
df['Genre'] = (
    df['Genre']
    .astype(str)
    .str.strip()
    .str.title()
)

In [ ]:
#Handle Special Formatting
df['Genre'] = df['Genre'].replace({
    "Role Playing":"Role-playing",
    "Role-Playing":"Role-playing"
})

In [ ]:
df['Platform'].unique()

array(['Nintendo Switch', 'PlayStation', 'PC', 'Xbox', 'Mobile'],
      dtype=object)

In [ ]:
#Standardize Platform
df['Platform'] = (
    df['Platform']
    .astype(str)
    .str.strip()
  )

In [ ]:
#Handle Special Formatting
df['Platform'] =df['Platform'].replace({
    "playstation": "PlayStation",
    "PLAYSTATION": "PlayStation",
    "pc":"PC",
    "PC":"PC",
    "xbox":"Xbox",
    "mobile":"Mobile",
    "nintendo switch":"Nintendo Switch"
})

In [ ]:
df['Platform']

0       Nintendo Switch
1       Nintendo Switch
2       Nintendo Switch
3           PlayStation
4                    PC
             ...
4995                 PC
4996             Mobile
4997             Mobile
4998               Xbox
4999        PlayStation
Name: Platform, Length: 5000, dtype: object

In [ ]:
#Create Decade Feature
df['Decade'] = (
    (df['Release Year']//10)*10
).astype(int).astype(str) + "s"